### ISSUE TITLE
fix bug in null check for qtip existence (surfaced after upgrading to jquery 1.4.2)

### ISSUE THREAD

**Issue by brianmario** [dustmoo/qtip#2]
```
@@ -131,7 +131,7 @@
             $.fn.qtip.interfaces[id] = obj;

             // Check if element already has qTip data assigned
-            if(typeof $(this).data('qtip') == 'object')
+            if($.isPlainObject($(this).data('qtip')))
             {
                // Set new current interface id
                if(typeof $(this).attr('qtip') === 'undefined')
```

The line numbers may be off a few since we're using a slightly modified version of rc3 (with tmm1's recent fix only) but you get the gist of the issue. On the changed line of code "$(this).data('qtip')" was returning null. And "typeof null" == "object" which was throwing an exception inside that if block.

**Comment by dustmoo** [comment]
Thanks for the fix! I have added it.

**Comment by brianmario** [comment]
sweet!
