### ISSUE TITLE
tip corner position

### ISSUE THREAD

**Issue by petermallett** [dustmoo/qtip#5]
When the position adjust option is set:
position: {adjust: {screen: true}}
Horizontal position adjustment updates the tip corner properly to the opposite side of the tip.  However, when the position adjusts vertically due to scrolling, the tip corner remains in the default position instead of shifting to the top or bottom corner appropriately.

**Comment by dustmoo** [comment]
Interesting, because the position should adjust automatically. What version of jQuery?

**Comment by petermallett** [comment]
This is using jQuery 1.4.  I will try to setup an example page on Monday.
